### ISSUE TITLE
Pruebas con navegador headless

### ISSUE THREAD

**Issue by UO244730** [Arquisoft/InciDashboard_e3b#10]
Para no tener problemas con el path de Firefox, sería buena idea usar un headless browser en nuestras pruebas.
Aquí hay un ejemplo de su uso:
https://github.com/Arquisoft/InciManager_e3b/blob/master/src/test/java/asw/selenium/SeleniumTest.java

**Comment by dalvgui** [comment]
Si has introducido ya el headless a las pruebas definidas anteriormente y son correctas, compruébalo y cierra la issue cuando lo consideres oportuno.
