### ISSUE TITLE
Mostrar todos los detalles de una incidencia

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/InciDashboard_e3b#12]
La vista de una incidencia tiene que mostrar todos los detalles.

Se puede copiar de la de detalles de inciManager: [ver aquí](https://github.com/Arquisoft/InciManager_e3b/blob/master/src/main/resources/templates/incidences/view.html).
![image](https://user-images.githubusercontent.com/17082987/38513219-ccc49832-3c2d-11e8-9964-74ad97cfef30.png)

Actualmente muestra nombre, descripción y localización:
![image](https://user-images.githubusercontent.com/17082987/38513312-16546716-3c2e-11e8-983c-9dff71b7773d.png)

**Comment by miguelms95** [comment]
Falta por mostrar todos los detalles de la incidencia. Todavía no está.

**Comment by dalvgui** [comment]
Para hacer el controlador, ¿ estás usando alguna rama para luego integrarlo en master ?
Me asigno para el tema del controlador, lo hablado.

**Comment by miguelms95** [comment]
Yo estoy trabajando desde la rama de `ejecucion-manual` con hsqldb. Haz los cambios donde mejor te venta (una rama propia u otra), y ya los actualizo yo en esa rama.

**Comment by dalvgui** [comment]
Para el controlador no hay que modificar nada le pasamos a la incidencia donde sacamos toda la inforamción de la incidencia que  muestras en la vista, le pasamos también todos los estados posibles para que el operario modifique en el caso necesario su estado y la localización procesada en dos campos distintos para localizarla con la api de google maps.

**Comment by miguelms95** [comment]
Ya está en master, finiquitado.

![image](https://user-images.githubusercontent.com/17082987/42000862-5f071bf8-7a62-11e8-99c7-46c582a649fb.png)
