### ISSUE TITLE
Visualizar incidencias no asignadas

### ISSUE THREAD

**Issue by UO244730** [Arquisoft/InciDashboard_e3b#15]
Se debe poder visualizar las incidencias no asignadas, de otra manera no se pueden ver aquellas que se han recibido de InciManager

**Comment by dalvgui** [comment]
Las incidencias cuando llegan al sistema se asignan, una incidencia no puede estar sin asignar a un operario.

**Comment by UO244730** [comment]
¿Cómo puedo ver a qué operario se asigna? ¿No hay alguna forma de escoger a quién se envía?

**Comment by UO244730** [comment]
Cierro la issue y abro otra para la automatización de la asignación de incidencias.
