### ISSUE TITLE
Configurar PostgreSQL como base de datos del proyecto

### ISSUE THREAD

**Issue by kilianpg** [Arquisoft/InciDashboard_e3b#17]

**Comment by UO244730** [comment]
Aparte de cambiar las dependencias y el fichero de properties, ¿cuál sería el proceso?

**Comment by kilianpg** [comment]
Creo que con eso basta, échale un vistazo a la rama [issue-postgres-db](https://github.com/Arquisoft/Agents_e3b/tree/issue-postgres-db) del repositorio Agents. Mientras tanto voy a cambiar la contraseña por defecto de Postgres a "changeit" en la imagen Docker del repositorio Inci_e3b_modules.

**Comment by UO244730** [comment]
Lo he dejado en la rama [postgresql](https://github.com/Arquisoft/InciDashboard_e3b/tree/postgresql). Voy a hacer un script para windows, aunque no podré probarlo.
