### ISSUE TITLE
Añadir botón travis

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/InciDashboard_e3b#4]
Añadir el botón de travis (badge) que apunta a la url de vuestro repositorio https://travis-ci.org/Arquisoft/InciDashboard_e3b en el README.md

**Comment by UO244730** [comment]
El build da errores
`[ERROR] /home/travis/build/Arquisoft/InciDashboard_e3b/src/main/java/inciDashboard/listeners/IncidenceListener.java:[11,1] package org.json does not exist`
Creo que es maven lo que da problemas, ¿alguien me puede ayudar?

**Comment by miguelms95** [comment]
Ese paquete parece que no existe (según dice el error), ¿Está hardcodeado de un copia y pega en la clase java?. Puedes intentar quitarlo, ejecuta los test para ver si funciona todo como debería, y si va bien, adelante. En caso de que fallen los test avisa y vemos...

**Comment by miguelms95** [comment]
Otra cosa: en el POM tenéis esta dependencia solo (que no se donde la estáis utilizando):

```
<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
		</dependency>
```

Mira a ver si existe una dependencia de Maven para **org.json** e importala, así travis se lo descarga y debería funcionar...

--
Edito: Veo ese error aquí: https://serverfault.com/questions/783552/package-org-json-does-not-exist, lo que busca es el JAR, que sería lo mismo que añadir la dependencia en pom.xml, así que será eso. Tienes que añadir esta dependencia en el pom.xml, la he buscado, así que solo copia y pega:

```
<!-- https://mvnrepository.com/artifact/org.json/json -->
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20180130</version>
</dependency>
```
