### ISSUE TITLE
README, pasos para ejecutar y datos de acceso al módulo

### ISSUE THREAD

**Issue by dalvgui** [Arquisoft/InciDashboard_e3b#8]
Introducir la secuencia de pasos para ejecutar el modulo, así como el puerto configurado y el software extra funcionando(kakfa,hsqldb).

**Comment by miguelms95** [comment]
Añadir también el tema de qué usuario de prueba se puede utilizar para hacer login (como Operario, etc...), para no tener que ir a la clase del código a investigar la combinación user/password y poder probar el módulo rápidamente.
